"""Initial migration

Revision ID: 557329850ccc
Revises: 
Create Date: 2024-06-01 22:18:32.552760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557329850ccc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weaviate_collection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weaviate_collection_collection_name'), 'weaviate_collection', ['collection_name'], unique=True)
    op.create_table('weaviate_object',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['weaviate_collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weaviate_object')
    op.drop_index(op.f('ix_weaviate_collection_collection_name'), table_name='weaviate_collection')
    op.drop_table('weaviate_collection')
    # ### end Alembic commands ###
